version: '3.8'

services:
  frontend:
    image: node:latest
    container_name: frontend
    restart: always
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - 5173:5173